controller_manager:
  ros__parameters:
    update_rate: 30 

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    crobot_drive_controller:
      type: crobot_controller/CrobotDriveController

    # sweeper_position_controller:
    #   type: position_controllers/JointGroupPositionController

    # winch_velocity_controller:
    #   type: velocity_controllers/JointGroupVelocityController

crobot_drive_controller:
  ros__parameters:
    wheel_joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - back_left_wheel_joint
      - back_right_wheel_joint
    
    ankle_joints:
      - front_left_ankle_joint
      - front_right_ankle_joint
      - back_left_ankle_joint
      - back_right_ankle_joint

    sweeper_joint: sweeper_joint
    winch_joint: winch_joint

    flagdropper_joint: flagdropper_joint
    
    imu_joint: base_to_imu_joint

    wheel_separation_width: 0.175     # 175mm left-right
    wheel_separation_length: 0.237    # 237mm front-back
    wheel_radius: 0.035               # 35mm radius

    max_ankle_angle: 1.5708           # rad (90 degrees) - maximum steering angle
    assumed_servo_speed_: 1.8      # rad/s - estimated maximum servo slew rate (actual value is probably 90 deg/s)

    max_linear_velocity: 0.5          # m/s
    max_angular_velocity: 1.5         # rad/s

    enable_odom_tf: false
    odom_frame_id: odom
    base_frame_id: base_link

    # use ~ for namespace
    cmd_vel_topic: /cmd_vel
    odom_topic: ~/odom                # will be /crobot_drive_controller/odom
    sweeper_topic: /sweeper_position_controller/commands
    winch_topic: /winch_velocity_controller/commands

    flagdropper_topic: /flagdropper_controller/commands

    ankle_min_angles: [-1.885, -0.524, -0.436, -1.728]  # [FL, FR, BL, BR]
    ankle_max_angles: [ 0.471,  1.676,  1.920,  0.628]

# sweeper_position_controller:
#   ros__parameters:
#     joints:
#       - sweeper_joint

# winch_velocity_controller:
#   ros__parameters:
#     joints:
#       - winch_joint